# Generated by Django 5.2.8 on 2025-11-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graftapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('retailer', 'Retailer'), ('winery', 'Winery'), ('admin', 'Admin')], max_length=20),
        ),
    ]
