# Generated by Django 5.2.8 on 2025-11-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graftapi', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('retailer', 'Retailer'), ('producer', 'Producer'), ('admin', 'Admin')], max_length=20),
        ),
    ]
