# Generated by Django 5.2.8 on 2025-11-15 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graftapi', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StoreChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('headquarters_city', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(blank=True, max_length=255)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='graftapi.storechain')),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('varietal', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('vintage', models.IntegerField(blank=True, null=True)),
                ('bottle_size_ml', models.IntegerField(default=750)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graftapi.producer')),
            ],
        ),
        migrations.CreateModel(
            name='RetailSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bottles_sold', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graftapi.store')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graftapi.wine')),
            ],
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('bottles_on_hand', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graftapi.store')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graftapi.wine')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('cases', models.IntegerField()),
                ('bottles_per_case', models.IntegerField(default=12)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graftapi.store')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graftapi.wine')),
            ],
        ),
        migrations.CreateModel(
            name='StorePlacementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('low', 'Low Stock'), ('inactive', 'Inactive')], max_length=20)),
                ('estimated_bottles', models.IntegerField(default=0)),
                ('last_sale_date', models.DateField(blank=True, null=True)),
                ('last_delivery_date', models.DateField(blank=True, null=True)),
                ('estimated_days_left', models.IntegerField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graftapi.store')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graftapi.wine')),
            ],
            options={
                'unique_together': {('store', 'wine')},
            },
        ),
    ]
