# Generated by Django 5.2.8 on 2026-02-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graftapi', '0006_store_contact_email_store_user_alter_store_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeplacementstatus',
            options={'verbose_name': 'Store Placement Status', 'verbose_name_plural': 'Store Placement Statuses'},
        ),
    ]
