# Generated by Django 5.2.8 on 2026-02-20 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graftapi', '0007_alter_storeplacementstatus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('stage', models.CharField(choices=[('requested', 'Requested'), ('outreach', 'Outreach'), ('tasting_scheduled', 'Tasting Scheduled'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('fit_score', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_requests', to='graftapi.producer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('email', 'Email Campaign'), ('instagram', 'Instagram Post'), ('shelf_talker', 'Shelf Talker'), ('one_sheet', 'One Sheet'), ('tasting_card', 'Tasting Card')], max_length=20)),
                ('prompt_used', models.TextField()),
                ('generated_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_materials', to='graftapi.producer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetailContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_contacts', to='graftapi.producer')),
            ],
        ),
        migrations.CreateModel(
            name='WholesalePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_effective', models.DateField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_prices', to='graftapi.store')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_prices', to='graftapi.wine')),
            ],
            options={
                'ordering': ['-date_effective'],
            },
        ),
    ]
