# Generated by Django 5.2.8 on 2026-03-10 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graftapi', '0009_grapespeciesprofile_scansession_pestdiseasedetection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VigilMLModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Cluster Volume Model', max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('training', 'Training'), ('ready', 'Ready'), ('failed', 'Failed'), ('archived', 'Archived')], default='training', max_length=20)),
                ('algorithm', models.CharField(default='ridge-regression-v1', max_length=100)),
                ('target', models.CharField(default='cluster_volume_cm3', max_length=100)),
                ('artifact_path', models.CharField(blank=True, max_length=500)),
                ('feature_schema', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('training_sample_count', models.PositiveIntegerField(default=0)),
                ('validation_sample_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vigil_ml_models', to='graftapi.producer')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('producer', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='VigilInferenceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(blank=True, max_length=255)),
                ('image', models.FileField(upload_to='vigil/inference/%Y/%m/%d/')),
                ('grape_species', models.CharField(blank=True, max_length=255)),
                ('predicted_volume_cm3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predicted_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_results', to='graftapi.vineyardblock')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vigil_inference_results', to='graftapi.producer')),
                ('scan_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_results', to='graftapi.scansession')),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='graftapi.vigilmlmodelversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VigilTrainingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(blank=True, max_length=255)),
                ('image', models.FileField(upload_to='vigil/training/%Y/%m/%d/')),
                ('grape_species', models.CharField(blank=True, max_length=255)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('target_volume_cm3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('occlusion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hanging_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bbox_width_px', models.IntegerField(blank=True, null=True)),
                ('bbox_height_px', models.IntegerField(blank=True, null=True)),
                ('berry_count', models.IntegerField(blank=True, null=True)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('vine_number', models.IntegerField(blank=True, null=True)),
                ('weather_temp_f', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('recent_rain_in', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('soil_moisture_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_samples', to='graftapi.vineyardblock')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vigil_training_samples', to='graftapi.producer')),
                ('scan_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_samples', to='graftapi.scansession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
