# Generated by Django 5.2.8 on 2026-03-19 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graftapi", "0010_vigilmlmodelversion_vigilinferenceresult_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockMoistureTarget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_min_pct", models.DecimalField(decimal_places=1, default=22.0, max_digits=5)),
                ("target_max_pct", models.DecimalField(decimal_places=1, default=28.0, max_digits=5)),
                ("critical_min_pct", models.DecimalField(decimal_places=1, default=18.0, max_digits=5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("block", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="moisture_target", to="graftapi.vineyardblock")),
            ],
        ),
        migrations.CreateModel(
            name="IrrigationRecommendation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("horizon_days", models.PositiveIntegerField()),
                ("action", models.CharField(choices=[("increase", "Increase"), ("schedule", "Schedule"), ("maintain", "Maintain"), ("reduce", "Reduce"), ("skip", "Skip")], max_length=20)),
                ("recommended_total_gallons", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("recommended_gallons_per_acre", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("next_irrigation_date", models.DateField(blank=True, null=True)),
                ("target_moisture_pct", models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ("confidence_score", models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ("drivers", models.JSONField(blank=True, default=dict)),
                ("explanation", models.TextField(blank=True)),
                ("block", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="irrigation_recommendations", to="graftapi.vineyardblock")),
            ],
            options={
                "ordering": ["-generated_at", "horizon_days"],
            },
        ),
        migrations.CreateModel(
            name="SoilMoistureReading",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recorded_at", models.DateTimeField()),
                ("moisture_pct", models.DecimalField(decimal_places=1, max_digits=5)),
                ("source", models.CharField(choices=[("manual", "Manual"), ("csv", "CSV Import")], default="manual", max_length=20)),
                ("source_label", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("block", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="soil_moisture_readings", to="graftapi.vineyardblock")),
            ],
            options={
                "ordering": ["-recorded_at", "-id"],
                "unique_together": {("block", "recorded_at", "moisture_pct", "source")},
            },
        ),
    ]
