from django.db import models

from .agriculture import VineyardBlock


class BlockMoistureTarget(models.Model):
    """Target moisture band used by the irrigation advisor."""

    block = models.OneToOneField(
        VineyardBlock, on_delete=models.CASCADE, related_name="moisture_target"
    )
    target_min_pct = models.DecimalField(max_digits=5, decimal_places=1, default=22.0)
    target_max_pct = models.DecimalField(max_digits=5, decimal_places=1, default=28.0)
    critical_min_pct = models.DecimalField(max_digits=5, decimal_places=1, default=18.0)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.block.name} moisture target"


class SoilMoistureReading(models.Model):
    """A soil-moisture reading captured manually or imported from CSV."""

    SOURCE_CHOICES = [
        ("manual", "Manual"),
        ("csv", "CSV Import"),
    ]

    block = models.ForeignKey(
        VineyardBlock, on_delete=models.CASCADE, related_name="soil_moisture_readings"
    )
    recorded_at = models.DateTimeField()
    moisture_pct = models.DecimalField(max_digits=5, decimal_places=1)
    source = models.CharField(max_length=20, choices=SOURCE_CHOICES, default="manual")
    source_label = models.CharField(max_length=255, blank=True)
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-recorded_at", "-id"]
        unique_together = ["block", "recorded_at", "moisture_pct", "source"]

    def __str__(self):
        return f"{self.block.name} {self.moisture_pct}% @ {self.recorded_at:%Y-%m-%d %H:%M}"


class IrrigationRecommendation(models.Model):
    """Recommendation snapshot generated by the irrigation advisor."""

    ACTION_CHOICES = [
        ("increase", "Increase"),
        ("schedule", "Schedule"),
        ("maintain", "Maintain"),
        ("reduce", "Reduce"),
        ("skip", "Skip"),
    ]

    block = models.ForeignKey(
        VineyardBlock, on_delete=models.CASCADE, related_name="irrigation_recommendations"
    )
    generated_at = models.DateTimeField(auto_now_add=True)
    horizon_days = models.PositiveIntegerField()
    action = models.CharField(max_length=20, choices=ACTION_CHOICES)
    recommended_total_gallons = models.DecimalField(
        max_digits=10, decimal_places=2, null=True, blank=True
    )
    recommended_gallons_per_acre = models.DecimalField(
        max_digits=10, decimal_places=2, null=True, blank=True
    )
    next_irrigation_date = models.DateField(null=True, blank=True)
    target_moisture_pct = models.DecimalField(max_digits=5, decimal_places=1, null=True, blank=True)
    confidence_score = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    drivers = models.JSONField(default=dict, blank=True)
    explanation = models.TextField(blank=True)

    class Meta:
        ordering = ["-generated_at", "horizon_days"]

    def __str__(self):
        return f"{self.block.name} {self.horizon_days}d {self.action}"
