from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from .views import (
    RegisterView,
    login_user,
    ProducerProfileView,
    ProducerWineView,
    ProducerWineDetailView,
    StoreProfileView,
    MyStoreView,
    MyStoreDetailView,
    PurchasingInsightsView,
    ai_chat,
    ProducerSummaryView,
    OrderingPredictionsView,
    PricingAnalyticsView,
    TargetingInsightsView,
    LocationRequestView,
    LocationRequestDetailView,
    RetailContactView,
    RetailContactDetailView,
    generate_marketing,
    MarketingHistoryView,
)
from .views_vigil import (
    VineyardView,
    VineyardDetailView,
    VineyardBlockView,
    VineyardBlockDetailView,
    ScanSessionView,
    ScanSessionDetailView,
    GrapeClusterView,
    PestDiseaseDetectionView,
    WeatherDataView,
    IrrigationLogView,
    IrrigationLogDetailView,
    GrapeSpeciesProfileView,
    YieldEstimateView,
    YieldEstimateDetailView,
    VigilDashboardSummaryView,
    VigilTrainingSampleView,
    VigilTrainingSampleDetailView,
    VigilMLModelVersionView,
    VigilModelTrainView,
    VigilModelTrainProgressView,
    VigilInferenceView,
    VigilDatasetSourceView,
    VigilDatasetImportView,
)

from .legal_insight_views import (
    legal_insight_chat,
    legal_insight_form_automator_generate,
    legal_insight_input_map,
    legal_insight_logic_trees,
    legal_insight_state_profiles,
    legal_insight_upload_document,
)

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", login_user, name="login"),
    path("producer-profile/", ProducerProfileView.as_view(), name="producer_profile"),
    path("store-profile/", StoreProfileView.as_view(), name="store_profile"),
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    # Mounted under /api/ at the project level
    path("my-wines/", ProducerWineView.as_view(), name="my-wines"),
    path("my-wines/<int:pk>/", ProducerWineDetailView.as_view(), name="my-wines-detail"),
    path("my-stores/", MyStoreView.as_view(), name="my-stores"),
    path("my-stores/<int:pk>/", MyStoreDetailView.as_view(), name="my-stores-detail"),
    path("purchasing-insights/", PurchasingInsightsView.as_view(), name="purchasing-insights"),
    # AI Chat endpoint
    path("ai/chat/", ai_chat, name="ai_chat"),
    # Producer dashboard endpoints
    path("producer-summary/", ProducerSummaryView.as_view(), name="producer-summary"),
    path("ordering-predictions/", OrderingPredictionsView.as_view(), name="ordering-predictions"),
    path("pricing-analytics/", PricingAnalyticsView.as_view(), name="pricing-analytics"),
    path("targeting-insights/", TargetingInsightsView.as_view(), name="targeting-insights"),
    path("location-requests/", LocationRequestView.as_view(), name="location-requests"),
    path("location-requests/<int:pk>/", LocationRequestDetailView.as_view(), name="location-requests-detail"),
    path("retail-contacts/", RetailContactView.as_view(), name="retail-contacts"),
    path("retail-contacts/<int:pk>/", RetailContactDetailView.as_view(), name="retail-contacts-detail"),
    path("marketing/generate/", generate_marketing, name="marketing-generate"),
    path("marketing/history/", MarketingHistoryView.as_view(), name="marketing-history"),

    # Legal Insight MVP endpoints (under /api/)
    path("legal-insight/state-profiles/", legal_insight_state_profiles, name="legal-insight-state-profiles"),
    path("legal-insight/logic-trees/", legal_insight_logic_trees, name="legal-insight-logic-trees"),
    path("legal-insight/input-map/<str:state_code>/", legal_insight_input_map, name="legal-insight-input-map"),
    path("legal-insight/form-automator/generate/", legal_insight_form_automator_generate, name="legal-insight-form-automator-generate"),
    path("legal-insight/chat/", legal_insight_chat, name="legal-insight-chat"),
    path("legal-insight/documents/upload/", legal_insight_upload_document, name="legal-insight-documents-upload"),
    # VIGIL endpoints
    path("vigil/summary/", VigilDashboardSummaryView.as_view(), name="vigil-summary"),
    path("vigil/vineyards/", VineyardView.as_view(), name="vigil-vineyards"),
    path("vigil/vineyards/<int:pk>/", VineyardDetailView.as_view(), name="vigil-vineyards-detail"),
    path("vigil/blocks/", VineyardBlockView.as_view(), name="vigil-blocks"),
    path("vigil/blocks/<int:pk>/", VineyardBlockDetailView.as_view(), name="vigil-blocks-detail"),
    path("vigil/scans/", ScanSessionView.as_view(), name="vigil-scans"),
    path("vigil/scans/<int:pk>/", ScanSessionDetailView.as_view(), name="vigil-scans-detail"),
    path("vigil/clusters/", GrapeClusterView.as_view(), name="vigil-clusters"),
    path("vigil/pest-detections/", PestDiseaseDetectionView.as_view(), name="vigil-pest-detections"),
    path("vigil/weather/", WeatherDataView.as_view(), name="vigil-weather"),
    path("vigil/irrigation/", IrrigationLogView.as_view(), name="vigil-irrigation"),
    path("vigil/irrigation/<int:pk>/", IrrigationLogDetailView.as_view(), name="vigil-irrigation-detail"),
    path("vigil/species-profiles/", GrapeSpeciesProfileView.as_view(), name="vigil-species-profiles"),
    path("vigil/yield-estimates/", YieldEstimateView.as_view(), name="vigil-yield-estimates"),
    path("vigil/yield-estimates/<int:pk>/", YieldEstimateDetailView.as_view(), name="vigil-yield-estimates-detail"),
    path("vigil/ml/training-samples/", VigilTrainingSampleView.as_view(), name="vigil-ml-training-samples"),
    path("vigil/ml/training-samples/<int:pk>/", VigilTrainingSampleDetailView.as_view(), name="vigil-ml-training-samples-detail"),
    path("vigil/ml/models/", VigilMLModelVersionView.as_view(), name="vigil-ml-models"),
    path("vigil/ml/train/", VigilModelTrainView.as_view(), name="vigil-ml-train"),
    path("vigil/ml/models/<int:model_id>/progress/", VigilModelTrainProgressView.as_view(), name="vigil-ml-model-progress"),
    path("vigil/ml/predictions/", VigilInferenceView.as_view(), name="vigil-ml-predictions"),
    path("vigil/ml/datasets/", VigilDatasetSourceView.as_view(), name="vigil-ml-datasets"),
    path("vigil/ml/datasets/<str:dataset_key>/import/", VigilDatasetImportView.as_view(), name="vigil-ml-dataset-import"),
]
